version: "3"
services:
  mailmenot:
    container_name: mailmenot
    build:
      context : ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    expose:
      - "3000"

networks:
  default:
    external:
      name: nginx-proxy-manager_default